name: CI Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Super-fast linting check
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js with PNPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm lint

  # Job 2: Type checking
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js with PNPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run TypeScript check
        run: pnpm run typecheck

  # Job 3: Architecture Fitness Function
  architecture:
    name: Architecture Fitness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for baseline comparison
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js with PNPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run architecture fitness function (strict mode)
        run: pnpm run analyze:modules:strict
      - name: Check baseline (if exists)
        run: |
          if [ -f .baseline-modules.json ]; then
            echo "Baseline found, checking for regressions..."
            pnpm run analyze:modules:ci
          else
            echo "No baseline found, skipping baseline check"
          fi

  # Job 4: End-to-End tests (parallelized by feature)
  e2e:
    name: E2E Tests (${{ matrix.feature }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Run all features even if one fails
      matrix:
        feature:
          - smoke.test
          - documents
          - editing
          - color
          - theme
          - feature-flags
          - sharing
          - scroll-sync
          - document-persistence
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js with PNPM cache
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(pnpm list @playwright/test --depth=0 --parseable | sed 's/.*@//' | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps chromium

      - name: Start dev server and run E2E tests
        run: |
          pnpm run dev &
          SERVER_PID=$!
          sleep 15
          NODE_OPTIONS='--import tsx' pnpm exec cucumber-js tests/features/${{ matrix.feature }}.feature
          kill $SERVER_PID
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.feature }}
          path: playwright-report/
          retention-days: 7
