name: CI Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '22'

permissions:
  contents: read
  checks: write
  pull-requests: write
  actions: read

defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Job 1: Super-fast linting check
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run ESLint
        run: pnpm lint

  # Job 2: Type checking
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run TypeScript check
        run: pnpm run typecheck

  # Job 3: Architecture Fitness Function
  architecture:
    name: Architecture Fitness
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for baseline comparison
      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run architecture fitness function (strict mode)
        run: pnpm run analyze:modules:strict
      - name: Check baseline (if exists)
        run: |
          if [ -f .baseline-modules.json ]; then
            echo "Baseline found, checking for regressions..."
            pnpm run analyze:modules:ci
          else
            echo "No baseline found, skipping baseline check"
          fi

  # Job 4: End-to-End tests (parallelized by feature)
  e2e:
    name: E2E Tests (${{ matrix.feature }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false # Run all features even if one fails
      matrix:
        feature:
          - smoke.test
          - documents
          - editing
          - color
          - theme
          - feature-flags
          - sharing
          - scroll-sync
          - document-persistence
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm and cache
        id: pnpm-setup
        uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache-playwright: 'true'

      - name: Install Playwright browsers
        if: steps.pnpm-setup.outputs.playwright-cache-hit != 'true'
        run: pnpm exec playwright install chromium --with-deps

      - name: Start dev server
        run: pnpm run dev &

      - name: Wait for dev server
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run E2E tests
        run: NODE_OPTIONS='--import tsx' pnpm exec cucumber-js tests/features/${{ matrix.feature }}.feature
        env:
          CI: true

      - name: Stop dev server
        if: always()
        run: pkill -f "pnpm run dev" || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.feature }}-${{ github.run_id }}
          path: playwright-report/
          retention-days: 7
