name: Test All E2E

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  NODE_VERSION: '22'
  PNPM_VERSION: 9.9.0

permissions:
  contents: read
  checks: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: e2e-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  e2e:
    name: E2E Tests (${{ matrix.feature }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        feature:
          - smoke.test
          - documents
          - editing
          - color
          - theme
          - feature-flags
          - sharing
          - scroll-sync
          - document-persistence
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm-install
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          cache-playwright: 'true'

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Start dev server
        run: pnpm run dev &

      - name: Wait for dev server
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run E2E tests
        run: NODE_OPTIONS='--import tsx' pnpm exec cucumber-js tests/features/${{ matrix.feature }}.feature
        env:
          CI: true

      - name: Stop dev server
        if: always()
        run: pkill -f "pnpm run dev" || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-report-${{ matrix.feature }}-${{ github.run_id }}
          path: playwright-report/
          retention-days: 7
